// Code generated by hertz generator.

package main

import (
	"context"
	"flag"
	"log"
	"os"
	"time"

	"github.com/cloudwego/hertz/pkg/app/server"
	hertzconfig "github.com/cloudwego/hertz/pkg/common/config"
	handler "github.com/gogogo1024/novagate/services/acl/biz/handler"
	"github.com/gogogo1024/novagate/services/acl/internal/acl"
	"github.com/redis/go-redis/v9"
)

func main() {
	var configPath string
	flag.StringVar(&configPath, "config", os.Getenv("ACL_CONFIG"), "path to yaml config (or set ACL_CONFIG)")
	flag.Parse()

	cfg, _, err := loadConfig(configPath)
	if err != nil {
		log.Fatalf("load config: %v", err)
	}

	handler.SetStatsEnabled(cfg.Server.EnableStats)

	opts := []hertzconfig.Option{}
	if cfg.Server.Addr != "" {
		opts = append(opts, server.WithHostPorts(cfg.Server.Addr))
	}

	// Choose store based on config.
	if cfg.Redis.Addr != "" {
		dial, read, write, err := cfg.redisTimeouts()
		if err != nil {
			log.Fatalf("invalid redis timeouts: %v", err)
		}

		rdb := redis.NewClient(&redis.Options{
			Addr:         cfg.Redis.Addr,
			Password:     cfg.Redis.Password,
			DB:           cfg.Redis.DB,
			DialTimeout:  dial,
			ReadTimeout:  read,
			WriteTimeout: write,
		})
		defer func() { _ = rdb.Close() }()

		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
		defer cancel()
		if err := rdb.Ping(ctx).Err(); err != nil {
			log.Fatalf("redis ping failed: %v", err)
		}

		handler.SetStore(acl.NewRedisStore(rdb, cfg.Redis.KeyPrefix))
	} else {
		handler.SetStore(acl.NewInMemoryStore())
	}

	h := server.Default(opts...)

	register(h)
	h.Spin()
}
