// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/gogogo1024/novagate/services/acl/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// ACL API (MVP)
	r.POST("/v1/acl/check-batch", handler.ACLCheckBatch)
	r.GET("/v1/acl/grants", handler.ACLListGrants)
	r.POST("/v1/acl/grant", handler.ACLGrant)
	r.POST("/v1/acl/revoke", handler.ACLRevoke)
	r.POST("/v1/acl/revoke-all", handler.ACLRevokeAllUser)
	r.GET("/v1/acl/stats", handler.ACLStats)

	// your code ...
}
